import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../src/components/Layout";
import { Title } from "@mantine/core";
import { FoodList } from "../src/components/FoodList";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title order={1}>Food App</Title>

      <FoodList />
    </Layout>
  );
};

export default Home;
