import type { NextPage } from "next";
import Head from "next/head";
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import { Layout } from "../src/components/Layout";
import { FoodList } from "../src/components/FoodList";

import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import Account from "../src/components/Auth/Account";
// import { createClient } from "@supabase/supabase-js";
import { useEffect, useState } from "react";
import { FoodT } from "../src/components/FoodList/types";
// import SignInWithEmail from "../src/components/Auth/SignInWithEmail";

const Home: NextPage = () => {
  const session = useSession();
  const supabase = useSupabaseClient();
  const [foods, setFoods] = useState<FoodT[]>([]);

  useEffect(() => {
    const getFoodsData = async () => {
      const { data: foods } = await supabase.from("foods").select("*");
      setFoods(foods as FoodT[]);
    };

    getFoodsData();
  }, []);

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {!session ? (
        <>
          {!signInWithEmail && (
            <>
              <Auth
                supabaseClient={supabase}
                appearance={{ theme: ThemeSupa }}
                theme="light"
              />
              <button
                type="button"
                onClick={() => {
                  setSignInWithEmail(true);
                }}
              >
                sign in with email
              </button>
            </>
          )}

          {signInWithEmail && (
            <>
              <SignInWithEmail supabase={supabase} />
              <button
                type="button"
                onClick={() => {
                  setSignInWithEmail(false);
                }}
              >
                sign in with email and password
              </button>
            </>
          )}
        </>
      ) : (
        <Account session={session} />
      )} */}

      {!session ? (
        <>
          <Auth
            supabaseClient={supabase}
            appearance={{ theme: ThemeSupa }}
            theme="light"
          />
        </>
      ) : (
        <Account session={session} />
      )}

      <FoodList foods={foods} />
    </Layout>
  );
};

export default Home;
